### ISSUE TITLE
API Key in your unit tests

### ISSUE THREAD

**Issue by ontraportgithub** [preluigi/OntraportPHP#2]
Probably want to hide that behind a config =). Looks pretty good though.

**Comment by preluigi** [comment]
Hi, the issue was fixed with commit b0d16d7cac78b5901551ce59404ef6ca63fe8643 and will be included in the next version 0.1.2

Thank you for pointing out the problem.

**Comment by ontraportgithub** [comment]
You're still putting the keys in the code.... you need to hide it or it
allows others access to that account.

On Tue, Nov 24, 2015 at 12:36 AM, Luigi Pressello notifications@github.com
wrote:

> Hi, the issue was fixed with commit b0d16d7
> https://github.com/preluigi/OntraportPHP/commit/b0d16d7cac78b5901551ce59404ef6ca63fe8643
> and will be included in the next version 0.1.2
> 
> Thank you for pointing out the problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/preluigi/OntraportPHP/issues/2#issuecomment-159195585
> .

## 

_Pin Chen__CTO_

## 

http://ontraport.com/

_Phone:_ (855) 668-7276
_Web: *ONTRAPORT.com http://www.ontraport.com/ 
*Social:_ facebook.com/ontraport http://www.facebook.com/ontraport

Read the latest from the ONTRAPORT Blog. http://blog.ontraport.com

**Comment by preluigi** [comment]
these are old disabled keys.
