### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by REPTILEHAUS** [preluigi/OntraportPHP#3]
Trying to run the examples given within Laravel and Im coming up against this error:

FatalErrorException in Contacts.php line 8: syntax error, unexpected 'protected' (T_PROTECTED)

**Comment by preluigi** [comment]
Hi padjodev, sorry, but this project is not active anymore since I don't own an active Ontraport subscription.
If anyone will donate a license for development purposes in the future I will go ahead with the development.
