### ISSUE TITLE
Object type id's

### ISSUE THREAD

**Issue by oakwoodgates** [preluigi/OntraportPHP#4]
Where are you getting these from, for example the "16"? 
`class Products extends Objects {
    protected static $object_id = 16;
}`

Thanks!

**Comment by preluigi** [comment]
Hi oakwoodgates, you can get the id by the `meta` endpoint in the ontraport API; I can't get more precise since this project is not active anymore.
If anyone will donate a license for development purposes in the future I will go ahead with the development.
